version: "3.1"
services:
  mariadb:
    image: mariadb:10.6.8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel-mgt-system
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3308:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]

  keycloak:
    image: jboss/keycloak:16.1.1
    environment:
      DB_VENDOR: mariadb
      DB_ADDR: mariadb
      DB_PORT: 3306
      DB_DATABASE: hotel-mgt-system
      DB_USER: root
      DB_PASSWORD: root
      KEYCLOAK_USER: root
      KEYCLOAK_PASSWORD: root
      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
      PROXY_ADDRESS_FORWARDING: "false"
      TZ: Asia/Colombo
    depends_on:
      - mariadb
    ports:
      - 8081:8080
