spring:
  application:
    name: hotel-mgt-api
  profiles:
      active: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 9008
  error:
    whitelabel:
      enabled: false
  max-http-header-size: 10MB

