spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/temp1?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true
    username: postgres
    password: root

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      show_sql: false
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
      connection:
        characterEncoding: utf-8
        CharSet: utf-8
        useUnicode: true
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
    exchange: user.exchange
    routing-key: user.routingkey
    queue: user.queue

  mail:
    host: smtp.gmail.com
    port: 587
    username: shanilersohtech@gmail.com
    password: buhsrofkfyhdszup
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true

#    Other props
queue:
  name-email: queue-email
  exchange: hotel-exchange
  route: hotel-route

