spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/temp1?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true
    username: postgres
    password: root

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      show_sql: false
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
      connection:
        characterEncoding: utf-8
        CharSet: utf-8
        useUnicode: true

